### ISSUE TITLE
Latest logdevice docker image is not starting up due to missing  libprotocol.so 

### ISSUE THREAD

**Issue by vvutharkar** [facebookincubator/LogDevice#143]
docker run -it --name mycluster facebookincubator/logdevice
/usr/local/bin/ld-dev-cluster: error while loading shared libraries: libprotocol.so: cannot open shared object file: No such file or directory

The latest image I am using is https://hub.docker.com/layers/facebookincubator/logdevice/latest/images/sha256-89e64c166dd2c6e12104d6c31bec29ee598ad9d07433876915e21a4788c21383

**Comment by MohamedBassem** [comment]
We’re currently doing some major refactoring on our source build which lead to some instabilities. @AhmedSoliman is fixing them as we speak, for now, you can use the release images instead of the latest tag.

**Comment by MohamedBassem** [comment]
@AhmedSoliman I assume this is fixed by now?

**Comment by AhmedSoliman** [comment]
@MohamedBassem My last diff that fixes everything is still landing, will let you know once we have a valid build on dockerhub.

**Comment by AhmedSoliman** [comment]
This particular issue if fixed though but ldshell might still have problems without my latest fixes.

**Comment by AhmedSoliman** [comment]
This is now resolved.
